### PR TITLE
Noted supporting PHP 7

### PR DESCRIPTION
**Pull request by matsubo**

### CODE REVIEW

**Comment by issei-m** [comment]
I'm not sure it works on 7.1. I'm gonna test ASAP, so please wait awhile :)

**Comment by matsubo** [comment]
ok. Thanks.

It worked on my demo page using this library.
https://matsu.teraren.com/spike-api-demo-php/

```
  % php -v
PHP 7.1.0 (cli) (built: Dec  2 2016 11:32:42) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0, Copyright (c) 1999-2016, by Zend Technologies
You have new mail.

```

**Comment by issei-m** [comment]
Cool! Meanwhile, I also have confirmed it works fine on Travis: https://github.com/issei-m/spike-php/pull/5
This PR can be merged.

**Comment by issei-m** [comment]
Thank you @matsubo

**Pull request merged**
